// to add project to server's database
export const ADD_QUESTION_TO_DATABASE = "ADD_QUESTION_TO_DATABASE";
export const GET_ALL_QUESTIONS_FROM_DATABASE =
  "GET_ALL_QUESTIONS_FROM_DATABASE";
export const ADD_ALL_QUESTIONS_FROM_DATABASE_TO_STORE =
  "ADD_ALL_QUESTIONS_FROM_DATABASE_TO_STORE";
export const ADD_NEW_QUESTION_FROM_DATABASE_TO_STORE =
  "ADD_NEW_QUESTION_FROM_DATABASE_TO_STORE";
// delete below
export const UPDATE_CURRENT_QUESTION_IN_STORE =
  "UPDATE_CURRENT_QUESTION_IN_STORE";
//   export const UPDATE_CURRENT_QUESTION_IN_STORE =

export const GET_CURRENT_QUESTION_FROM_DATABASE =
  "GET_CURRENT_QUESTION_FROM_DATABASEC";
export const DELETE_QUESTION_FROM_DATABASE = "DELETE_QUESTION_FROM_DATABASE";
export const DELETE_QUESTION_FROM_STORE = "DELETE_QUESTION_FROM_STORE";
// issue actions
export const ADD_ISSUE_TO_QUESTION_IN_DATABASE =
  "ADD_ISSUE_TO_QUESTION_IN_DATABASE";
export const UPDATE_ASSIGNEE_FOR_ISSUE_IN_DATABASE =
  "UPDATE_ASSIGNEE_FOR_ISSUE_IN_DATABASE";

// action to update  reqStatusReturnedFromServer: "", reqMessageReturnedFromServer: null,
export const UPDATE_REQ_INFO_RETURNED_FROM_SERVER =
  "UPDATE_REQ_INFO_RETURNED_FROM_SERVER";

export const ADD_SUBMISSION_TO_QUESTION = "ADD_SUBMISSION_TO_QUESTION";
